plugins:
  - jekyll-relative-links
title: Barclay Kamaleson
logo: ./assets/imgs/000102740017.jpg
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-minimal
